[tool.poetry]
name = "poetry-instance"
version = "2.1.1"
description = ""
authors = []
license = ""
package-mode = false

[tool.poetry.dependencies]
python = "3.11.2"
poetry = "2.1.1"

[tool.poetry.group.additional.dependencies]
poetry-plugin-shell = "^1.0.1"

