[tool.poetry]
name = "poetry-instance"
version = "2.1.2"
description = ""
authors = []
license = ""
package-mode = false

[tool.poetry.dependencies]
python = "3.13.7"
poetry = "^2.1.4"

[tool.poetry.group.additional.dependencies]
poetry-plugin-shell = "^1.0.1"

